# top level stuff you probably don't need to touch
highlighter: pygments
markdown: redcarpet
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true


# edit here to achieve your personal greatness
url: http://dkarter.github.io/
baseurl: /blog/
title: Dorian Karter
author: Dorian Karter
description: Personal blog and resume
avatar: profile.jpg
email: jobs@doriankerter.com
github: dkarter
twitter: dorian_escplan
linkedin: doriankarter
stackoverflow: users/77131/dorian
#Comment out if you don't want disqus 
# disqus: username
google_analytics: UA-38677517-1


# needed for travis-ci build
exclude: [vendor]
